

CREATE DATABASE LOCADORA;
GO

USE LOCADORA;
GO

CREATE TABLE EMPRESA(
	idEmpresa INT PRIMARY KEY IDENTITY(1,1),
	nomeEmpresa VARCHAR(30)
);
GO

CREATE TABLE VEICULO(
	idVeiculo INT PRIMARY KEY IDENTITY(1,1),
	idEmpresa INT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
	placaVeiculo VARCHAR(10) NOT NULL  
);
GO


CREATE TABLE MODELO(
	idModelo INT PRIMARY KEY IDENTITY(1,1),
	idVeiculo INT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
	nomeModelo VARCHAR(10) NOT NULL,
	anoModelo VARCHAR(4) NOT NULL
);
GO


CREATE TABLE MARCA(
	idMarca INT PRIMARY KEY IDENTITY(1,1),
	idModelo INT FOREIGN KEY REFERENCES MODELO(idModelo),
	nomeMarca VARCHAR(15) NOT NULL
);
GO


CREATE TABLE CLIENTE(
	idCliente INT PRIMARY KEY IDENTITY(1,1),
	nomeCliente VARCHAR(30)
);
GO


CREATE TABLE ALUGUEL(
	idAluguel INT PRIMARY KEY IDENTITY(1,1),
	idVeiculo INT FOREIGN KEY REFERENCES VEICULO(idVeiculo),
	idCliente INT FOREIGN KEY REFERENCES CLIENTE(idCliente),
	nomeCliente VARCHAR(30),
	tipoCarro VARCHAR(15),
	dataAluguel DATE
);
GO