

CREATE DATABASE PCLINICS;
GO

USE PCLINICS;
GO

CREATE TABLE CLINICAVETERINARIA(
	idClinicaveterinaria INT PRIMARY KEY IDENTITY(1,1),
	endereco VARCHAR(40) NOT NULL
);
GO


CREATE TABLE VETERINARIO(
	idVeterinario INT PRIMARY KEY IDENTITY(1,1),
	idClinicaveterinaria INT FOREIGN KEY REFERENCES CLINICAVETERINARIA(idClinicaveterinaria),
	nomeVeterinario VARCHAR(25) NOT NULL
);
GO


CREATE TABLE PET(
	idPet INT PRIMARY KEY IDENTITY(1,1),
	nomePet VARCHAR(10) NOT NULL
);
GO


CREATE TABLE CONSULTA(
	idConsulta INT PRIMARY KEY IDENTITY(1,1),
	idVeterinario INT FOREIGN KEY REFERENCES VETERINARIO(idVeterinario),
	idPet INT FOREIGN KEY REFERENCES PET(idPet),
	dataConsulta DATE,
	nomeVeterinario VARCHAR(25) NOT NULL,
	pet VARCHAR(10) NOT NULL
);
GO


CREATE TABLE DONO(
	idDono INT PRIMARY KEY IDENTITY(1,1),
	idPet INT FOREIGN KEY REFERENCES PET(idPet),
	nomeDono VARCHAR(30),
	nomePet VARCHAR(10)
);
GO

CREATE TABLE RACA(
	idRaca INT PRIMARY KEY IDENTITY(1,1),
	idPet INT FOREIGN KEY REFERENCES PET(idPet),
	nomeRaca VARCHAR(15),
	nomePet VARCHAR(15)
);
GO


CREATE TABLE TIPOPET(
	idTipopet INT PRIMARY KEY IDENTITY(1,1),
	idRaca INT FOREIGN KEY REFERENCES RACA(idRaca),
	tipoPet VARCHAR(15)
);
GO
